listener {
    timeout = 60                            # in seconds
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 65                             # 5 min 30 sec
    on-timeout = hyprctl dispatch dpms off  
    on-resume = hyprctl dispatch dpms on
}
